name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/egrissino/gateway-sdk-image:latest

    steps:
    - uses: actions/checkout@v4

    - name: Checkout project
      run: git clone https://github.com/egrissino/gateway-app.git && cd gateway-app

    - name: Configure CMake
      run: ./configure.sh

    - name: Build
      run: ./build.sh
